version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_flask_app
    ports:
      - "5001:5000"
    depends_on:
      - db
    volumes:
      - ./app:/usr/src/app

  db:
    image: postgres:latest
    container_name: my_postgres_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=mytodos
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
